# Generated by Django 3.2.9 on 2022-01-30 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Vendor_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Vendorlists', to='api.vendor'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Catagories', to='api.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SubCats', to='api.subcategory'),
        ),
    ]
